// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Endable is an autogenerated mock type for the Endable type
type Endable struct {
	mock.Mock
}

// End provides a mock function with no fields
func (_m *Endable) End() {
	_m.Called()
}

// NewEndable creates a new instance of Endable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEndable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Endable {
	mock := &Endable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
