// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	log "github.com/smallhouse123/go-library/service/log"
	mock "github.com/stretchr/testify/mock"
)

// Log is an autogenerated mock type for the Log type
type Log struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Log) Close() {
	_m.Called()
}

// WriteLog provides a mock function with given fields: logName, requestEvent
func (_m *Log) WriteLog(logName string, requestEvent *log.RequestEvent) {
	_m.Called(logName, requestEvent)
}

// NewLog creates a new instance of Log. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *Log {
	mock := &Log{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
